version: '3'
services:
  db:
    build: ./db
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234

  mail:
    build: ./mail
    container_name: mail
    environment:
      - PORT=5000
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USER=xxxxxxxx
      - MAIL_DEST_USER=xxx.xxx@gmail.com
      - MAIL_PASSWORD=xxxxxxxxxxx
    ports:
      - 5000:5000

  api:
    build: ./api
    container_name: api
    environment:
      - PG_USER=postgres
      - PG_DATABASE=microservice
      - PG_PASS=1234
      - PG_HOST=db
      - PG_PORT=5432
      - API_PREFIX=/
      - API_PORT=4000
    ports:
      - 4000:4000
    links:
      - db
      - mail

  front:
    build: ./front
    container_name: front
    tty: true
    ports:
      - 3000:3000
    links:
      - api
