version: '3'
services:
  db:
    build: ./db
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234

  api:
    build: ./api
    container_name: api
    environment:
      - PG_USER=postgres
      - PG_DATABASE=microservice
      - PG_PASS=1234
      - PG_HOST=db
      - PG_PORT=5432
      - API_PREFIX=/
      - API_PORT=4000
    ports:
      - 4000:4000
    links:
      - db

  front:
    build: ./front
    container_name: front
    tty: true
    ports:
      - 3000:3000
    links:
      - api
